name: notification_channel_manager_example
description: Demonstrates how to use the notification_channel_manager plugin.
publish_to: "none"

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  notification_channel_manager:
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
