name: notification_channel_manager
description: An Android plugin to Manage (CRUD) NotificationChannels and NotificationChannelGroups.
version: 0.0.4-dev+0
homepage: https://github.com/imedboumalek/notification_channel_manager.git
repository: https://github.com/imedboumalek/notification_channel_manager.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # notification_channel_manager_example:
  #   path: example
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.imed.notification_channel_manager
        pluginClass: NotificationChannelManagerPlugin
