name: notification_channel_manager
description: An Android plugin to Manage (CRUD) NotificationChannels and NotificationChannelGroups.
version: 0.0.3-dev+0
homepage: https://github.com/imedboumalek/notification_channel_manager.git
repository: https://github.com/imedboumalek/notification_channel_manager.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.notification_channel_manager
        pluginClass: NotificationChannelManagerPlugin
